### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
!pip install tensorflow-gpu

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
sent

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[256, 459, 158, 130], [256, 459, 158, 29], [256, 34, 158, 262], [191, 131, 459, 324, 150], [191, 131, 459, 324, 117], [70, 256, 340, 158, 121], [110, 142, 424, 324]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [16]:
## pre padding 
#(sent_length=8) now it will make each doucuments size equal to 8 either adding fonrt or adding back(pre & post)
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 256 459 158 130]
 [  0   0   0   0 256 459 158  29]
 [  0   0   0   0 256  34 158 262]
 [  0   0   0 191 131 459 324 150]
 [  0   0   0 191 131 459 324 117]
 [  0   0   0  70 256 340 158 121]
 [  0   0   0   0 110 142 424 324]]


In [17]:
## 10 feature dimesnions
dim=10


In [23]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [25]:
model.build(input_shape=(None, sent_length))


In [26]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 256, 459, 158, 130], dtype=int32)

In [30]:
#model.predict(embedded_docs[0])
model.predict(embedded_docs[0].reshape(1, -1))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step


array([[[-0.01408218, -0.04184358, -0.01768235, -0.01862301,
          0.02720964, -0.03113412, -0.01928778, -0.02018884,
          0.0373495 , -0.04419193],
        [-0.01408218, -0.04184358, -0.01768235, -0.01862301,
          0.02720964, -0.03113412, -0.01928778, -0.02018884,
          0.0373495 , -0.04419193],
        [-0.01408218, -0.04184358, -0.01768235, -0.01862301,
          0.02720964, -0.03113412, -0.01928778, -0.02018884,
          0.0373495 , -0.04419193],
        [-0.01408218, -0.04184358, -0.01768235, -0.01862301,
          0.02720964, -0.03113412, -0.01928778, -0.02018884,
          0.0373495 , -0.04419193],
        [-0.0260645 ,  0.04457464,  0.02662445, -0.01511338,
          0.04619311, -0.00639349, -0.01453079,  0.00772757,
          0.00759317, -0.04355798],
        [ 0.02932507, -0.02260201,  0.04700868, -0.01890935,
          0.00083898, -0.01810529,  0.00854491,  0.00721275,
         -0.03150222,  0.03325902],
        [ 0.04961834, -0.01638038,  0.04194144,  0.0

In [31]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[[[-0.01408218 -0.04184358 -0.01768235 -0.01862301  0.02720964
   -0.03113412 -0.01928778 -0.02018884  0.0373495  -0.04419193]
  [-0.01408218 -0.04184358 -0.01768235 -0.01862301  0.02720964
   -0.03113412 -0.01928778 -0.02018884  0.0373495  -0.04419193]
  [-0.01408218 -0.04184358 -0.01768235 -0.01862301  0.02720964
   -0.03113412 -0.01928778 -0.02018884  0.0373495  -0.04419193]
  [-0.01408218 -0.04184358 -0.01768235 -0.01862301  0.02720964
   -0.03113412 -0.01928778 -0.02018884  0.0373495  -0.04419193]
  [-0.0260645   0.04457464  0.02662445 -0.01511338  0.04619311
   -0.00639349 -0.01453079  0.00772757  0.00759317 -0.04355798]
  [ 0.02932507 -0.02260201  0.04700868 -0.01890935  0.00083898
   -0.01810529  0.00854491  0.00721275 -0.03150222  0.03325902]
  [ 0.04961834 -0.01638038  0.04194144  0.02243939  0.04894146
    0.02964598  0.01045962 -0.00213005 -0.02547028 -0.00889922]
  [-0.0263249  -0.03019526 -0.00886698  0.01325544  0.02451685
    0.0361

In [32]:
embedded_docs[0]

array([  0,   0,   0,   0, 256, 459, 158, 130], dtype=int32)

In [33]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
[[-0.01408218 -0.04184358 -0.01768235 -0.01862301  0.02720964 -0.03113412
  -0.01928778 -0.02018884  0.0373495  -0.04419193]
 [-0.01408218 -0.04184358 -0.01768235 -0.01862301  0.02720964 -0.03113412
  -0.01928778 -0.02018884  0.0373495  -0.04419193]
 [-0.01408218 -0.04184358 -0.01768235 -0.01862301  0.02720964 -0.03113412
  -0.01928778 -0.02018884  0.0373495  -0.04419193]
 [-0.01408218 -0.04184358 -0.01768235 -0.01862301  0.02720964 -0.03113412
  -0.01928778 -0.02018884  0.0373495  -0.04419193]
 [-0.0260645   0.04457464  0.02662445 -0.01511338  0.04619311 -0.00639349
  -0.01453079  0.00772757  0.00759317 -0.04355798]
 [ 0.02932507 -0.02260201  0.04700868 -0.01890935  0.00083898 -0.01810529
   0.00854491  0.00721275 -0.03150222  0.03325902]
 [ 0.04961834 -0.01638038  0.04194144  0.02243939  0.04894146  0.02964598
   0.01045962 -0.00213005 -0.02547028 -0.00889922]
 [-0.0263249  -0.03019526 -0.00886698  0.01325544  0.02451685  0.03619076
   0.03065891

In [34]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras